module.exports = class Ellia {
    constructor() {
        this.quotes = [
            "Hello, Summoner!",
            "Another lovely day!",
            "I was waiting for you!",
            "Tada!",
            "Durand is not employer-of-the-year material.",
            "I'm in such a good mood!",
            "What are you doing? Can I join? I'm just bored, that's all.",
            "See how clean the island is? You’re welcome!",
            "It feels bad to have unfinished daily missions.",
            "Boring! Boring! Boring!",
            "Tap and hold the Monster to move its location.",
            "What do you think about today's weather?",
            "I would love to be able to meet Goddess Ameria.",
            "The island itself tells a lot about its owner.",
            "I'm feeling great today!",
            "I think someone is gossiping about me...",
            "I heard that “Fried Chicken” is a magical cuisine.",
            "Crystals Giants are fluffy hearted creatures.",
            "Step forward if you are worthy...of what?",
            "I've heard there's a great monster out there!",
            "I think I gained weight... What do you think?",
            "I want to go home now...",
            "Edmund is NOT my type!",
            "Make sure to check in every day!",
            "Who's your favorite Monster? Huh?",
            "People say I'm clumsy. That can't be good, right?",
            "Let's take a look at the special Hall of Hoes!",
            "LF Seara SD.",
            "Where's my Zaiross?",
            "Nat5 pl0x.",
            "SALTCITY.",
            "One more devilmon pack and I'll be out on the streets.",
            "Slime OP",
            "One of these days Lushen will give me his business card.",
            "I wonder how many McChickens I could buy with all the money I spent on packs..."
        ];
    }
}